variable "env" {}
variable "tags" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "default_vpc_rt" {}
variable "allow_ssh_cidr" {}
variable "rabbitmq" {}
variable "zone_id" {}
variable "rds" {}